### ISSUE TITLE
Error line 10 in CVE20160728.py for Kali Linux 4.13.0 (super() takes at least 1 argument)

### ISSUE THREAD

**Issue by webpwnized** [spencerdodd/kernelpop#3]
root@kali:/opt/kernelpop# ls
constants.py  exploits  img  kernelpop.py  playground  README.md  src  test

root@kali:/opt/kernelpop# python kernelpop.py 

##########################
#  welcome to kernelpop  #
#                        #
# let's pop some kernels #
##########################

[+] underlying os identified as a linux variant
[+] kernel Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling identified as:
	type:			linux
	distro:			unknown
	version:		4.13-1
	architecture:		x86_64
[*] matching kernel to known exploits
Traceback (most recent call last):
  File "kernelpop.py", line 17, in <module>
    main()
  File "kernelpop.py", line 7, in main
    kernelpop()
  File "/opt/kernelpop/src/kernelpop.py", line 377, in kernelpop
    identified_exploits = find_exploit_locally(kernel_v)
  File "/opt/kernelpop/src/kernelpop.py", line 261, in find_exploit_locally
    exploit_instance = exploit_module()
  File "/opt/kernelpop/exploits/linux/CVE20160728.py", line 10, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

root@kali:/opt/kernelpop# uname -a
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux

**Comment by spencerdodd** [comment]
This is not an issue with kernelpop but with python versioning. The issue is because you are running the program with python2 instead of python3:
`python2`
<img width="799" alt="screen shot 2017-11-05 at 3 29 29 pm" src="https://user-images.githubusercontent.com/9969454/32418797-2ea8be80-c23e-11e7-8af7-68ed712862ab.png">
`python3`
<img width="783" alt="screen shot 2017-11-05 at 3 29 43 pm" src="https://user-images.githubusercontent.com/9969454/32418798-30ad824c-c23e-11e7-93bc-b5a33bc440f3.png">
python2 is not supported at this time.
